# Протокол JIM - поля:
jim_action = 'action'
jim_time = 'time'
jim_user = 'user'
jim_account_name = 'account_name'
jim_presence = 'presence'
jim_response = 'response'
jim_error = 'error'
jim_message = 'message'
jim_message_txt = 'mess_text'
jim_sender = 'from'
jim_waiter = 'to'
jim_exit = 'exit'
